-- Muster Mandanten: wer welchen Mandanten sieht.
--
-- Vierte Migration einer App aus der Vorlage. Sie setzt nur die 001 voraus,
-- die Tabelle `vorgaenge`; die 002 und 003 der Muster Dokumente und Auslesen
-- braucht sie nicht. Trägt die App schon eine eigene 004, bekommt diese Datei
-- die nächste freie Nummer, bevor sie an einem Gerät gelaufen ist. Eine
-- Migration, die einmal gelaufen ist, wird nie wieder angefasst.
--
-- Drei Tabellen und eine Spalte:
--
--   `mandanten`    wen die App kennt. Das Gerät kennt keine Mandanten und soll
--                  sie nicht kennen
--   `konten`       jeder Name, den die App in der Kopfzeile der Anmeldung
--                  gesehen hat. Der Schlüssel einer App kann die Konten des
--                  Geräts nicht auflisten; zugeordnet wird nur, wer schon
--                  einmal da war
--   `zuordnungen`  welches Konto welchen Mandanten sieht. Daraus kommt jeder
--                  Filter und jeder Kreis der Entscheider
--   `vorgaenge.mandant`  zu wem ein Vorgang gehört. Ohne Mandant sieht ihn
--                  niemand
--
-- Geschrieben, wie PostgreSQL es spricht; ohne Gerät übersetzt `ablage/db.mjs`
-- für SQLite. Zeiten stehen als Text im ISO-Format.

CREATE TABLE mandanten (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT    NOT NULL UNIQUE,
  angelegt_von TEXT    NOT NULL,
  angelegt     TEXT    NOT NULL
);

CREATE TABLE konten (
  -- Der Name aus der Kopfzeile, wie das Gerät ihn setzt. Nie aus einem
  -- Formularfeld.
  benutzer TEXT PRIMARY KEY,
  zuerst   TEXT NOT NULL,
  zuletzt  TEXT NOT NULL
);

CREATE TABLE zuordnungen (
  benutzer       TEXT    NOT NULL,
  mandant        INTEGER NOT NULL REFERENCES mandanten (id),
  zugeordnet_von TEXT    NOT NULL,
  seit           TEXT    NOT NULL,
  PRIMARY KEY (benutzer, mandant)
);

-- Der Filter fragt je Anfrage, welche Mandanten ein Name sieht.
CREATE INDEX zuordnungen_nach_mandant ON zuordnungen (mandant);

ALTER TABLE vorgaenge ADD COLUMN mandant INTEGER REFERENCES mandanten (id);
CREATE INDEX vorgaenge_nach_mandant ON vorgaenge (mandant, id DESC);
