-- Muster Mandanten: wer einen Mandanten sieht, und wer über seine Vorgänge
-- entscheidet, sind zwei Dinge.
--
-- Setzt die 030 voraus. Eine App, die sie schon als 006-entscheider.sql trägt,
-- behält die alte Datei.
--
-- **Die Nummern der Muster kollidieren nicht.** Die Vorlage hält 001 bis 009, jedes Muster
-- einen eigenen Zehner: Dokumente 010, Auslesen 020, Mandanten 030 und 031, Belege 040.
-- Eigene Migrationen der App beginnen bei 100. Bis Kit 0.74.0 trugen Vorlage und Muster
-- Dokumente beide eine 002, und wer drei Muster zusammensetzte, sortierte von Hand.
--
-- **Sehen heißt nicht entscheiden.** In einer Kanzlei sehen zehn Kollegen einen
-- Mandanten, und freigeben darf nur der Partner, der ihn betreut. Bis Kit 0.41.0
-- war jeder Zugeordnete Entscheider, und zwei Sachbearbeiter gaben sich
-- gegenseitig frei: vier Augen, die keine waren.
--
-- Die Spalte steht an der Zuordnung, nicht am Konto: wer bei Müller entscheidet,
-- entscheidet nicht deshalb bei Schmidt. Vorgabe ist 0. Eine App, die diese
-- Migration nachträglich bekommt, hat danach keinen Entscheider, bis die
-- Verwaltung einen markiert, und jeder Vorgang bleibt mit dem Satz dazu in
-- Arbeit: lieber keine Freigabe als eine vom Falschen.

ALTER TABLE zuordnungen ADD COLUMN entscheidet INTEGER NOT NULL DEFAULT 0;
