-- Muster Dokumente: die Tabelle, in der hochgeladene Dateien liegen.
--
-- Zweite Migration einer App aus der Vorlage. Die Nummer vorn gibt die
-- Reihenfolge, und wer die 001 schon hat, bekommt beim nächsten Start genau
-- diese hier dazu. Eine Migration, die einmal gelaufen ist, wird nie wieder
-- angefasst.
--
-- Die Bytes liegen IN der Datenbank und nicht daneben in einem Ordner: am Gerät
-- ist die Datenbank der eine Ort, der das nächste Einspielen überlebt, und das
-- Dateisystem des Containers ist es nicht. So steht es im Kontrakt unter
-- `daten`. Geschrieben, wie PostgreSQL es spricht; ohne Gerät übersetzt
-- `ablage/db.mjs` für SQLite.

CREATE TABLE dokumente (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Der Dateiname, wie der Mensch ihn kennt. Er steht in der Liste und in der
  -- Kopfzeile der Dokumentanzeige.
  name      TEXT    NOT NULL,
  -- Der MIME-Typ, wie der Browser ihn beim Hochladen genannt hat. Daran
  -- entscheidet die Oberfläche, ob die Dokumentanzeige ein PDF oder ein Bild
  -- vor sich hat.
  art       TEXT    NOT NULL,
  groesse   INTEGER NOT NULL,
  -- Wer hochgeladen hat. Kommt aus der Anmeldung des Geräts, nie aus dem
  -- Formular.
  von       TEXT    NOT NULL,
  abgelegt  TEXT    NOT NULL,
  inhalt    BYTEA   NOT NULL
);

-- Die Liste zeigt das Neueste oben und ohne die Bytes.
CREATE INDEX dokumente_nach_zeit ON dokumente (id DESC);
