-- Muster Dokumente: die Tabelle, in der hochgeladene Dateien liegen.
--
-- Setzt nur die Vorlage voraus. Die Nummer vorn gibt die Reihenfolge, und
-- wer die Vorlage schon hat, bekommt beim nächsten Start genau diese hier
-- dazu. Eine Migration, die einmal gelaufen ist, wird nie wieder angefasst.
-- Eine App, die diese Tabelle schon als 002-dokumente.sql trägt (Kit bis
-- 0.74.0), behält die alte Datei und bekommt diese nicht dazu.
--
-- **Die Nummern der Muster kollidieren nicht.** Die Vorlage hält 001 bis 009, jedes Muster
-- einen eigenen Zehner: Dokumente 010, Auslesen 020, Mandanten 030 und 031, Belege 040.
-- Eigene Migrationen der App beginnen bei 100. Bis Kit 0.74.0 trugen Vorlage und Muster
-- Dokumente beide eine 002, und wer drei Muster zusammensetzte, sortierte von Hand.
--
-- Die Bytes liegen IN der Datenbank und nicht daneben in einem Ordner: am Gerät
-- ist die Datenbank der eine Ort, der das nächste Einspielen überlebt, und das
-- Dateisystem des Containers ist es nicht. So steht es im Kontrakt unter
-- `daten`. Geschrieben, wie PostgreSQL es spricht; ohne Gerät übersetzt
-- `ablage/db.mjs` für SQLite.

CREATE TABLE dokumente (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Der Dateiname, wie der Mensch ihn kennt. Er steht in der Liste und in der
  -- Kopfzeile der Dokumentanzeige.
  name      TEXT    NOT NULL,
  -- Der MIME-Typ, wie der Browser ihn beim Hochladen genannt hat. Daran
  -- entscheidet die Oberfläche, ob die Dokumentanzeige ein PDF oder ein Bild
  -- vor sich hat.
  art       TEXT    NOT NULL,
  groesse   INTEGER NOT NULL,
  -- Wer hochgeladen hat. Kommt aus der Anmeldung des Geräts, nie aus dem
  -- Formular.
  von       TEXT    NOT NULL,
  abgelegt  TEXT    NOT NULL,
  inhalt    BYTEA   NOT NULL
);

-- Die Liste zeigt das Neueste oben und ohne die Bytes.
CREATE INDEX dokumente_nach_zeit ON dokumente (id DESC);
