-- Die erste Migration: die Tabelle, in der die Vorgänge liegen.
--
-- Eine Datei je Schritt, die Nummer vorn gibt die Reihenfolge. Eine Migration,
-- die einmal gelaufen ist, wird nie wieder angefasst: wer sie ändert, ändert
-- die Vergangenheit von Datenbanken, die es schon gibt. Was danach anders sein
-- soll, steht in 002.
--
-- Geschrieben, wie PostgreSQL es spricht, denn das ist die Datenbank am Gerät.
-- Ohne Gerät läuft dieselbe Datei in SQLite; was dafür übersetzt wird,
-- steht in `ablage/db.mjs`. Deshalb stehen Zeiten hier als Text im ISO-Format.

CREATE TABLE vorgaenge (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titel           TEXT    NOT NULL,
  text            TEXT    NOT NULL,
  -- Wer eingereicht hat. Kommt aus der Anmeldung des Geräts, nie aus einem
  -- Formularfeld.
  von             TEXT    NOT NULL,
  gestellt        TEXT    NOT NULL,
  status          TEXT    NOT NULL,
  -- Die Nummer des Laufs am Gerät. NULL heißt: es kam keiner zustande, und
  -- warum, steht in `hinweis`.
  lauf            TEXT,
  entschieden_von TEXT,
  begruendung     TEXT,
  bemerkung       TEXT,
  hinweis         TEXT
);

-- Die Liste zeigt das Neueste oben, und die Seite fragt nach, solange etwas
-- wartet. Beides liest über diesen Index.
CREATE INDEX vorgaenge_nach_stand ON vorgaenge (status, id DESC);
