-- Muster Dokument auslesen: jede Auslesung eines Dokuments, auch die, die
-- nicht gelang.
--
-- Dritte Migration einer App aus der Vorlage, nach 002 aus dem Muster
-- Dokumente, auf dessen Tabelle sie zeigt. Eine Migration, die einmal gelaufen
-- ist, wird nie wieder angefasst.
--
-- **Nur anhängen.** Jede Auslesung ist eine neue Zeile, keine wird geändert,
-- keine gelöscht, auch nicht mit dem Dokument. Gilt ist die neueste, die
-- gelang; die davor sind das Protokoll: welches Modell, wann, wie lange, auf
-- wessen Anstoß, mit welchem Ergebnis. Eine Auslesung, die niemand mehr
-- nachvollziehen kann, taugt nicht als Grundlage einer Buchung.
--
-- Geschrieben, wie PostgreSQL es spricht; ohne Gerät übersetzt `ablage/db.mjs`
-- für SQLite. Deshalb stehen Zeit und JSON als Text und die Texterkennung als
-- Zahl, 1 oder 0.

CREATE TABLE auslesungen (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Welches Dokument. Kein Fremdschlüssel mit Löschen: das Protokoll bleibt,
  -- auch wenn das Dokument geht.
  dokument_id   INTEGER NOT NULL,
  -- Wer die Auslesung angestoßen hat, aus der Anmeldung des Geräts.
  von           TEXT    NOT NULL,
  zeit          TEXT    NOT NULL,
  -- Was das Gerät dazu sagt: welches Modell die Felder gefüllt hat, wie lange
  -- es dauerte, ob die Texterkennung lief und wie viel Text sie fand.
  modell        TEXT,
  dauer_ms      INTEGER,
  texterkennung INTEGER,
  zeichen       INTEGER,
  -- Der Auftrag am Gerät (`job_id`). Unter derselben Nummer steht der Aufruf
  -- im Protokoll des Geräts, mit dem Menschen, für den er geschah.
  auftrag       TEXT,
  -- Die Felder als JSON, so wie das Modell sie gab. NULL, wenn keine kamen.
  felder        TEXT,
  -- Was die App an den Feldern auszusetzen hatte, als JSON-Liste von Sätzen.
  maengel       TEXT,
  -- Warum keine Felder kamen, in einem Satz, und was das Modell stattdessen
  -- schrieb.
  fehler        TEXT,
  roh           TEXT
);

CREATE INDEX auslesungen_nach_dokument ON auslesungen (dokument_id, id DESC);
