/**
 * Die Datenbank und ihre Migrationen.
 *
 * **Am Geraet ist es die Datenbank, die das Geraet der App gibt**: PostgreSQL,
 * eine je App und Stand, angelegt vom Geraet, ihre Adresse in dem
 * Umgebungswert, den der Kontrakt unter `umgebung.datenbank` nennt. Sie ist
 * der EINE Ort, der das naechste Einspielen, das Schalten und jeden Neustart
 * ueberlebt, und sie wird jede Nacht gesichert. Das Dateisystem des Containers
 * ist es nicht: das Geraet ersetzt den Container bei jedem Einspielen, samt
 * seiner Volumes. So steht es im Kontrakt unter `daten`.
 *
 * **Ohne Geraet ist es SQLite aus Node selbst** (`node:sqlite`), in einer
 * Datei neben dem Quelltext: fuer den Selbsttest des Kits, fuer einen Blick
 * auf dem eigenen Rechner und fuer `--compose` auf einem Geraet ohne Arasul.
 * Dort ueberlebt sie einen Neustart des Containers und nicht das naechste
 * Einspielen, und `/lage` sagt das.
 *
 * **Es gibt ein SQL, nicht zwei.** Geschrieben wird es so, wie PostgreSQL es
 * spricht, und SQLite versteht fast alles davon. Die Naht zu SQLite uebersetzt
 * genau zwei Dinge und keines mehr:
 *
 *   - Platzhalter: `$1` wird `?1`. Beide meinen den ersten Wert.
 *   - Die laufende Nummer einer Tabelle: `INTEGER GENERATED BY DEFAULT AS
 *     IDENTITY PRIMARY KEY` wird `INTEGER PRIMARY KEY AUTOINCREMENT`.
 *
 * Daraus folgen drei Regeln fuer jede Migration und jede Abfrage dieser App:
 * eine Zeit steht als Text im ISO-Format, JSON steht als Text und die Ablage
 * wandelt es, und Bytes stehen als `BYTEA`. Wer eine Funktion braucht, die nur
 * PostgreSQL kennt, braucht sie am Geraet und nirgends sonst; dann laeuft der
 * Selbsttest dieser Stelle nicht mehr, und das gehoert in die README der App.
 *
 * **Der Stand der Datenbank steht in ihr selbst**, in der Tabelle
 * `migrationen`. Eine Migration, die gelaufen ist, laeuft nicht noch einmal,
 * und eine, die fehlt, laeuft nach. Die Datenbank beginnt leer: ihr Schema legt
 * die App an, und das Geraet erlaubt es ihr, denn ihre Rolle ist Eigentuemerin.
 *
 * `pg` ist die eine Abhaengigkeit des Backends. Geladen wird es erst, wenn eine
 * Adresse da ist: ohne Geraet laeuft die App ohne einen einzigen Paketbaum.
 */

import { mkdirSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HIER = dirname(fileURLToPath(import.meta.url));
const MIGRATIONEN = join(HIER, "migrationen");

/** Die Migrationen in ihrer Reihenfolge. Die Nummer vorn im Dateinamen ist sie. */
export function migrationen(ordner = MIGRATIONEN) {
  return readdirSync(ordner)
    .filter((name) => name.endsWith(".sql"))
    .sort()
    .map((name) => ({ name, sql: readFileSync(join(ordner, name), "utf8") }));
}

const STAND_ANLEGEN = "CREATE TABLE IF NOT EXISTS migrationen (name TEXT PRIMARY KEY, angewandt TEXT NOT NULL)";

/** Was SQLite anders schreibt, und nur das. */
function fuerSqlite(sql) {
  return sql
    .replace(/INTEGER\s+GENERATED\s+(?:BY\s+DEFAULT|ALWAYS)\s+AS\s+IDENTITY\s+PRIMARY\s+KEY/gi, "INTEGER PRIMARY KEY AUTOINCREMENT")
    .replace(/\$(\d+)/g, "?$1");
}

/** Ein Wert, wie SQLite ihn binden kann: kein `undefined`, kein Wahrheitswert. */
function sqliteWert(wert) {
  if (wert === undefined) return null;
  if (typeof wert === "boolean") return wert ? 1 : 0;
  return wert;
}

/** Eine Zeile aus SQLite, mit Bytes als Buffer wie aus PostgreSQL. */
function sqliteZeile(zeile) {
  if (!zeile) return zeile;
  const aus = {};
  for (const [name, wert] of Object.entries(zeile)) aus[name] = wert instanceof Uint8Array ? Buffer.from(wert) : wert;
  return aus;
}

/** SQLite hinter derselben Naht wie PostgreSQL. */
async function sqlite(datei) {
  const { DatabaseSync } = await import("node:sqlite");
  mkdirSync(dirname(datei), { recursive: true });
  const roh = new DatabaseSync(datei);
  roh.exec("PRAGMA journal_mode = WAL");
  roh.exec("PRAGMA foreign_keys = ON");
  const vorbereitet = new Map();
  const anweisung = (sql) => {
    if (!vorbereitet.has(sql)) vorbereitet.set(sql, roh.prepare(fuerSqlite(sql)));
    return vorbereitet.get(sql);
  };
  return {
    art: "sqlite",
    dauerhaft: false,
    async abfrage(sql, werte = []) {
      return anweisung(sql).all(...werte.map(sqliteWert)).map(sqliteZeile);
    },
    async eine(sql, werte = []) {
      return sqliteZeile(anweisung(sql).get(...werte.map(sqliteWert))) ?? null;
    },
    async ausfuehren(sql, werte = []) {
      return Number(anweisung(sql).run(...werte.map(sqliteWert)).changes);
    },
    async migrieren(name, sql) {
      roh.exec("BEGIN");
      try {
        roh.exec(fuerSqlite(sql));
        roh.prepare("INSERT INTO migrationen (name, angewandt) VALUES (?, ?)").run(name, new Date().toISOString());
        roh.exec("COMMIT");
      } catch (fehler) {
        roh.exec("ROLLBACK");
        throw fehler;
      }
    },
    async schliessen() {
      roh.close();
    },
  };
}

/** PostgreSQL, die Datenbank des Geraets. */
async function postgres(adresse) {
  const { default: pg } = await import("pg");
  const pool = new pg.Pool({ connectionString: adresse, max: 5 });
  return {
    art: "postgres",
    dauerhaft: true,
    async abfrage(sql, werte = []) {
      return (await pool.query(sql, werte)).rows;
    },
    async eine(sql, werte = []) {
      return (await pool.query(sql, werte)).rows[0] ?? null;
    },
    async ausfuehren(sql, werte = []) {
      return (await pool.query(sql, werte)).rowCount ?? 0;
    },
    async migrieren(name, sql) {
      // Eine Verbindung fuer die ganze Migration: im Pool liefe jede Anweisung
      // womoeglich auf einer anderen, und die Transaktion gaelte fuer keine.
      const verbindung = await pool.connect();
      try {
        await verbindung.query("BEGIN");
        await verbindung.query(sql);
        await verbindung.query("INSERT INTO migrationen (name, angewandt) VALUES ($1, $2)", [name, new Date().toISOString()]);
        await verbindung.query("COMMIT");
      } catch (fehler) {
        await verbindung.query("ROLLBACK");
        throw fehler;
      } finally {
        verbindung.release();
      }
    },
    async schliessen() {
      await pool.end();
    },
  };
}

/**
 * Die Datenbank oeffnen und auf den neuesten Stand bringen.
 *
 * `adresse` ist die Adresse, die das Geraet in den Container gelegt hat; mit
 * ihr ist es PostgreSQL. Ohne sie ist es die Datei `datei`. Zurueck kommt sie
 * offen, mit dem, was angewandt wurde. Jede Migration laeuft in ihrer eigenen
 * Transaktion: bricht die dritte ab, sind die ersten beiden trotzdem drin, und
 * der naechste Start setzt genau dort wieder an.
 */
export async function oeffnen({ adresse = null, datei, ordner = MIGRATIONEN }) {
  const db = adresse ? await postgres(adresse) : await sqlite(datei);
  await db.ausfuehren(STAND_ANLEGEN);
  const gelaufen = new Set((await db.abfrage("SELECT name FROM migrationen")).map((zeile) => zeile.name));
  const angewandt = [];
  for (const migration of migrationen(ordner)) {
    if (gelaufen.has(migration.name)) continue;
    try {
      await db.migrieren(migration.name, migration.sql);
    } catch (fehler) {
      await db.schliessen();
      throw new Error(`Die Migration ${migration.name} ist nicht durchgelaufen: ${fehler.message}`);
    }
    angewandt.push(migration.name);
  }
  return { db, angewandt, stand: gelaufen.size + angewandt.length };
}
