-- Muster Verlauf: wer was wann an einem Vorgang getan hat. Es wird nur angehängt.
--
-- Der eigene Zehner des Musters ist 050 (Vorlage 001 bis 009, Dokumente 010, Auslesen 020,
-- Mandanten 030, Belege 040). Sie setzt nur die 001 der Vorlage voraus.
--
-- **Kein Weg ändert oder löscht eine Zeile.** Die Ablage `ablage/verlauf.mjs` kennt nur
-- `anhaengen` und `amVorgang`. Wer nachvollziehen will, wer was wann getan hat, muss sich darauf
-- verlassen können, dass das Gestern morgen noch so dasteht.
--
-- **Der Mandant steht nicht hier.** Gelesen wird der Verlauf nur über seinen Vorgang, und wer
-- den Vorgang nicht sieht, bekommt 404 (Muster Mandanten). So gibt es keinen zweiten Filter,
-- den eine Abfrage vergessen könnte.

CREATE TABLE verlauf (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vorgang INTEGER NOT NULL REFERENCES vorgaenge (id),
  -- Was geschah: angelegt, eingereicht, genehmigt, abgelehnt, abgelaufen, nicht gezählt,
  -- abgeschlossen, oder ein Wort der Fach-App.
  was     TEXT    NOT NULL,
  -- Wer es getan hat, aus der Anmeldung des Geräts. NULL, wenn es das Gerät selbst war.
  wer     TEXT,
  -- Was dazugehört, als JSON: die Begründung einer Ablehnung, die Änderungen am Vorschlag.
  angaben TEXT,
  -- Wann die App es erfuhr. Eine Entscheidung erfährt sie beim nächsten Nachziehen, Sekunden
  -- später; nennt das Gerät den Zeitpunkt, steht er in `angaben.entschieden_am`.
  zeit    TEXT    NOT NULL
);

CREATE INDEX verlauf_nach_vorgang ON verlauf (vorgang, id);
